trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.0.200' # ajuste conforme a versão do seu projeto .NET

- script: dotnet restore dotnet_projeto_devops.csproj
  displayName: 'dotnet restore'

- script: dotnet build dotnet_projeto_devops.csproj --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
